# Site settings
title: Dubai
client:
  name: Dubai Tourism
  link: https://www.visitdubai.com/en
core-se-link: https://www.secretescapes.com/current-sales
description: >
  The capital of the emirate of the same name is a global pioneer when it comes to architecture, shopping or comfort of the highest class. Find out where your favorite beach is, shop through world history and venture into the world of tomorrow at Expo 2020.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/dubai" # the subpath of the site, including territory and year
img:     "/uk/2020/dubai/_assets/img"
css:     "/uk/2020/dubai/_assets/css"
js:      "/uk/2020/dubai/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed